# Generated by Django 5.0.6 on 2024-05-16 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=255)),
                ('english_title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('summary', models.TextField()),
                ('is_adult', models.BooleanField()),
                ('genres', models.ManyToManyField(to='mooovie.genre')),
                ('keywords', models.ManyToManyField(to='mooovie.keyword')),
                ('languages', models.ManyToManyField(related_name='movies', to='mooovie.language')),
                ('original_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_language_movies', to='mooovie.language')),
                ('production_companies', models.ManyToManyField(to='mooovie.productioncompany')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooovie.actor')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooovie.character')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooovie.movie')),
            ],
        ),
    ]
